// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, name, apikey)
    VALUES ($1, $2, $3, $4, encode(sha256 (random()::text::bytea), 'hex'))
RETURNING
    id, created_at, updated_at, name, apikey
`

type CreateUserParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Apikey,
	)
	return i, err
}

const getAllByApiKey = `-- name: GetAllByApiKey :one
SELECT
    id, created_at, updated_at, name, apikey
FROM
    users
WHERE
    apikey = $1
`

func (q *Queries) GetAllByApiKey(ctx context.Context, apikey string) (User, error) {
	row := q.db.QueryRowContext(ctx, getAllByApiKey, apikey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Apikey,
	)
	return i, err
}

const getIdByApiKey = `-- name: GetIdByApiKey :one
SELECT
    id
FROM
    users
WHERE
    apikey = $1
`

func (q *Queries) GetIdByApiKey(ctx context.Context, apikey string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getIdByApiKey, apikey)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
